# pytorch_lightning==1.9.4
seed_everything: true
model:
  class_path: learn.models.GATModel
  init_args:
    in_channels: 38
    num_layers: 3
    hidden_channels: 128
    num_heads: 4
    out_channels: 4
    dropout: 0.01
    jk: cat
data:
  root: data
  batch_size: 32
  num_workers: 32
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.0001
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: torsionnet
        log_graph: true
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: hp_metric
        mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: hp_metric
        mode: min
        filename: "{epoch:02d}-{hp_metric:.2f}"
    - class_path: learn.callbacks.LogChiCallback
    - class_path: learn.callbacks.LogParametersCallback
  enable_progress_bar: true
  max_epochs: null
  log_every_n_steps: 1
  accelerator: gpu
  strategy: auto
  precision: 32
